openlineage: 
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('AIRFLOW_HOME') + '/openlineage.json' }}"
      project: openlineage
      dataset: metrics
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
